TARGETS = atractest decode getsoundsample getremainframe ids resetpos resetting setdata replay
EXTRA_OBJS = atrac-imports.o ../sascore/sascore-imports.o shared.o
EXTRA_LIBS = -lpspaudio

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
