var _vfs = require('./vfs/vfs');
_vfs.Vfs;
var _zip = require('./vfs/vfs_zip');
_zip.ZipVfs;
var _iso = require('./vfs/vfs_iso');
_iso.IsoVfs;
var _uri = require('./vfs/vfs_uri');
_uri.UriVfs;
var _ms = require('./vfs/vfs_ms');
_ms.MemoryStickVfs;
var _memory = require('./vfs/vfs_memory');
_memory.MemoryVfs;
var _mountable = require('./vfs/vfs_mountable');
_mountable.MountableVfs;
var _storage = require('./vfs/vfs_storage');
_storage.StorageVfs;
var _emulator = require('./vfs/vfs_emulator');
_emulator.EmulatorVfs;
var _dropbox = require('./vfs/vfs_dropbox');
_dropbox.DropboxVfs;
exports.FileMode = _vfs.FileMode;
exports.FileOpenFlags = _vfs.FileOpenFlags;
exports.Vfs = _vfs.Vfs;
exports.ProxyVfs = _vfs.ProxyVfs;
exports.VfsEntry = _vfs.VfsEntry;
exports.ZipVfs = _zip.ZipVfs;
exports.IsoVfs = _iso.IsoVfs;
exports.UriVfs = _uri.UriVfs;
exports.MemoryVfs = _memory.MemoryVfs;
exports.DropboxVfs = _dropbox.DropboxVfs;
exports.MountableVfs = _mountable.MountableVfs;
exports.StorageVfs = _storage.StorageVfs;
exports.EmulatorVfs = _emulator.EmulatorVfs;
exports.MemoryStickVfs = _ms.MemoryStickVfs;
//# sourceMappingURL=vfs.js.map