TARGETS = fonttest \
	altcharcode find fontinfo fontinfobyindex fontlist newlib open openfile openmem optimum resolution \
	charglyphimage charglyphimageclip charimagerect charinfo \
	shadowglyphimage shadowglyphimageclip shadowimagerect shadowinfo
EXTRA_OBJS = libfont-imports.o

COMMON_DIR = ../../common
include $(COMMON_DIR)/common.mk
