TARGETS = basic \
	create setpsmf setpsmfoffset settempbuf start \
	getaudiodata getaudiooutsize getvideodata update \
	break delete releasepsmf stop \
	configplayer playmode selectspecific selectstream \
	getcurrentpts getcurrentstatus getcurrentstream getpsmfinfo
EXTRA_OBJS = psmf-imports.o mpeg-imports.o shared.o

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
