TARGETS = threads create change extend exitstatus threadend release rotate refer stackfree start suspend terminate threadmanidlist threadmanidtype
EXTRA_OBJS = thread-imports.o

COMMON_DIR = ../../../common
include ../../../common/common.mk
